### ISSUE TITLE
json: cannot unmarshal bool into Go struct field .embed_code of type string

### ISSUE THREAD

**Issue by chneau** [tumblr/tumblr.go#6]
https://github.com/tumblr/tumblr.go/blob/01c315a92daab3e8af9df49da1363cc60421fa70/post.go#L181 

I guess it should be a bool instead of a string ?

```
json: cannot unmarshal bool into Go struct field .embed_code of type string
```

**Comment by jasonpenny** [comment]
`embed_code` should be a string, can you include the JSON here that the library fails to unmarshal?

**Comment by chneau** [comment]
So I get the error from the TaggedSearch.
Here is my piece of code:
```go
r.param.Set("before", strconv.FormatInt(r.date.Unix(), 10))
results, e := tumblr.TaggedSearch(r.client, r.tag, r.param)
```
I've added some extra logging here:
```go 
// gets page of posts
func TaggedSearch(client ClientInterface, tag string, params url.Values) (*SearchResults, error) {
	params.Set("tag", tag)
	response, err := client.GetWithParams("/tagged", params)
	if err != nil {
		return nil, err
	}
	result := struct {
		Response []MiniPost `json:"response"`
	}{}
	if err = json.Unmarshal(response.body, &result); err != nil {
		log.Println(string(response.body))
		return nil, err
	}
	minis := result.Response
	full := SearchResults{
		Posts:  makePostsFromMinis(minis, client),
		client: client,
		params: params,
	}
	if err = json.Unmarshal(response.body, &full); err != nil {
		log.Println(string(response.body))
		return nil, err
	}
	return &full, nil
}
```
and here is what I get:
https://jsoneditoronline.org/?id=ee90f137c58d42c6ab66bf6070413137 
You can find somewhere `"embed_code":false`.
It is actually on `.response[7]`. 
(which is basically this post http://animetube.tumblr.com/post/163255974438/sky-ninjas-invade-konoha-using-winged-mechanical (video doesn't work) if it can help, here is the id of the post `163255974438` )

**Comment by jasonpenny** [comment]
This should be fixed now if you update to the latest version
